### ISSUE TITLE
Electron v1.x support

### ISSUE THREAD

**Issue by jacobq** [mawie81/electron-window-state#7]
It appears that `electron-window-state` does not work with the `electron` version 1.x. Attempting to build a previously working project using `electron-window-state` v2.1.0 after upgrading `electron` from 0.37.8 to 1.0.1 gives an error like the following:
```
Error opening app
The app provided is not a valid Electron app, please read the docs on how to write one:
https://github.com/electron/electron/tree/v1.0.1/docs

Error: Cannot find module 'app'
```
If one then manually changes `node_modules\electron-window-state\index.js` to use `require('electron').app` instead of `require('app')` (e.g. line 3) then this error goes away and another appears, this time related to the `screen` module:
![screen-error](https://cloud.githubusercontent.com/assets/1633459/15187902/9cdf4a22-1768-11e6-942f-f907ec656ec2.png)

Once again, replacing `require('screen')` with `require('electron').screen` appears to resolve the problem....I guess I'll just make a PR for this now :)

**Comment by jacobq** [comment]
Actually, it looks like someone just beat me to it. Thanks for the fast work & feel free to close this.

**Comment by mawie81** [comment]
You are welcome :)
